apiVersion: v1
kind: Pod
metadata:
  name: demo-kotlinapp
  labels:
    role: webapp

spec:
  containers:
    - name: web
      image: rdiaz07/demo-kotlin:latest
      ports: 
        - containerPort: 80
          name: web
          protocol: TCP
